### ISSUE TITLE
Rhys TO-DO

### ISSUE THREAD

**Issue by Rhys-L** [Rhys-L/Final_Project_Group7#15]
- [x] Make bigquery table public
- [x] Connect Carter's model to the table
- [x] Connect Nongjie's model to the table
- [x] Write sections of Group Report
- [x] Write Individual Report
- [x] Contribute to slides
- [x] Clean up Git Repository
- [x] Add ReadMe
- [x] Add Better comments to the gather_data.py script.
