### ISSUE TITLE
Carter To-DO

### ISSUE THREAD

**Issue by Rhys-L** [Rhys-L/Final_Project_Group7#16]
- [x] Write sections of Group Report
- [x]  Write Individual Report
- [x]  Contribute to slides
