### ISSUE TITLE
Nongjie To-DO

### ISSUE THREAD

**Issue by Rhys-L** [Rhys-L/Final_Project_Group7#17]
- [x] Develop GUI for linear model 
- [x] Write sections of Group Report
- [x]  Write Individual Report
- [x]  Contribute to slides
